# Generated by Django 4.1.1 on 2022-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_kimlik_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kimlik",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
